## Load and draw the ROI locations generated by PalmKit

import os
import cv2
import numpy as np
import roiExtractor as kit



pathDB = '/media/sunny/CoolFish/exp/dataset/pklnet/ALL/xiaomi/test/image/'
pathIn = '/home/sunny/wk/exp7_hand/palmseg-test/rst_test'


pathROI1 = os.path.join(pathIn, 'roi')


pathKpPKL = os.path.join(pathIn, 'keypoints')
# pathKpKit = os.path.join(pathDB, 'keypionts')


files = sorted(os.listdir(pathKpPKL))

for name in files:
    print(name)
    basename = '.'.join(name.split('.')[:-1])
    im = cv2.imread(os.path.join(pathDB, basename+'.png'), 1)#--------------.png jpg

    ps = np.loadtxt(os.path.join(pathKpPKL, name))
    pt1 = ps[:2]
    pt2 = ps[2:4]

    # ps = np.array([0,0,0,0,0,1,1,1,1,0])
    # # ps = np.array([0,0,1,0,0,0,1,0,1,1])
    # pt1 = np.array([100, 100])
    # pt2 = np.array([100, 200])
    # print(ps, pt1, pt2)

    anticlock = kit.isAntiClock(ps[4:10])

    kps = kit.getROIckp(pt1, pt2, anticlock)
    # print(kps)
    roi = kit.getROIsmp(im, kps, 128)
    # print(roi)

    c1_ = tuple(pt1.astype(np.int32))
    c2_ = tuple(pt2.astype(np.int32))
    # print(c1_)

    r1_, r2_, r3_, r4_ = np.array(kps).astype(np.int32)

    r1_ = ps[4:6].astype(np.int32)
    r2_ = ps[6:8].astype(np.int32)
    r3_ = ps[8:10].astype(np.int32)
    r4_ = ps[10:12].astype(np.int32)

    cv2.line(im, r1_, r2_, thickness=3, color=(255,210,50))
    cv2.line(im, r2_, r3_, thickness=3, color=(255,210,50))
    cv2.line(im, r3_, r4_, thickness=3, color=(255,210,50))
    cv2.line(im, r4_, r1_, thickness=3, color=(255,210,50))

    cv2.circle(im, r1_, radius=5, thickness=-1, color=(255,0,0))
    cv2.circle(im, r2_, radius=5, thickness=-1, color=(0,0,0))
    cv2.circle(im, r3_, radius=5, thickness=-1, color=(0,255, 255))
    cv2.circle(im, r4_, radius=5, thickness=-1, color=(255,0,255))

    cv2.line(im, c1_, c2_, thickness=2, color=(255,210,50))

    cv2.circle(im, c1_, radius=5, thickness=-1, color=(0,0,255))
    cv2.circle(im, c2_, radius=5, thickness=-1, color=(0,255,0))


    cv2.imshow('img', im)
    cv2.imshow('roi', roi)
    cv2.waitKey(0)